### ISSUE TITLE
[REQ] 로컬환경에서의 Replication DB 구성

### ISSUE THREAD

**Issue by laigasus** [cloud2scape/on-premise#1]
## 기능

제 곧 내

## 설명

개발에서 Replication 작업 연결을 설정하고자 
구성환경을 제공해줄 것을 요청드립니다.

가능한 **one click provisioning** 환경 부탁드립니다 🙏

## 기대 효과

개발 애플리케이션에서 CQRS 패턴을 적용할 수 있습니다.

## 대안 방안

해당 기술로 구성된 클라우드를 제시해주셔도 좋습니다.

##  첨부 자료

개발자 시점에서의 접근 정보입니다.
RW DB 접근 정보, RO DB 접근 정보 가 필요합니다.

https://gist.github.com/laigasus/63f6e02653ca4e808262b746859ffbed

로컬에서 RW. RO 두 DB가 연결된 구성환경이 필요해요오
환경 세팅 도와주실 @tensorplumber 구해요~~

가능하신지요

_Originally posted by @laigasus in https://github.com/cloud2scape/.github/discussions/28_

**Comment by gimsoomin** [comment]
https://github.com/13rom/vagrant-mysql-master-slave-replication/tree/master
참고한 깃헙입니다.

1.master.sh 와 slave.sh 에서 각 ip를 마스터 ip로 바꾸고
2.Vagrantfile 주소를 각 master와 slave와 바꾼 후 
전체 파일을 몰아넣고 vagrant up하면 2개 vm이 생성되면서 각각 스크립트를 실행합니다

로컬에서 테스트하여 각각 rw, ro 되는 것 확인했습니다.
